# ~/.bashrc

# Variables
export LANG=en_GB.UTF-8
export EDITOR="nvim"
export HISTCONTROL="ignoredups:ignoreboth"
export HISTFILESIZE="5000"
export PROMPT_COMMAND="history -a"

# Aliases
alias ..='cd ..'
alias ...='cd ../../'
alias ax="chmod a+x"
alias cp='cp -iv'
alias ff='find . -type f -iname'
alias more="less"
alias ll="ls -lh"
alias ls="ls --color -hF"
alias lh='ls -lisAd .[^.]*'
alias hs='history|grep -i '
alias less="less -R --tabs=4"
alias mocp="mocp -T moca_theme"
alias mv="mv -i"
alias psf="ps aux | grep -v grep | grep $1"
alias rm='rm -Iv'
alias rms='shred -uz'
alias rs='rsync -avz --progress --delete-after'
alias tgz='tar -xvfz'
alias tbz='tar -jxvf'
alias zxf='tar -zxf'
alias unrar='rar e'
alias vim="nvim"
alias qiv="pqiv"

# Kubernetes aliases from https://ahmet.im/blog/kubectl-aliases/
alias k='kubectl'
alias kg='kubectl get'
alias kgpo='kubectl get pods'
alias kgpoj='kubectl get pods -o=json'
alias kgpon='kubectl get pods --namespace'
alias ksysgpooyamll='kubectl --namespace=kube-system get pods -o=yaml -l'
alias krm='kubectl delete'
alias krmf='kubectl delete -f'
alias krming='kubectl delete ingress'
alias krmingl='kubectl delete ingress -l'
alias krmingall='kubectl delete ingress --all-namespaces'

# Docker aliases
# Get latest container ID
alias dl="docker ps -l -q"

# Get container process
alias dps="docker ps"

# Get process included stop container
alias dpa="docker ps -a"

# Get images
alias di="docker images"

# Get container IP
alias dip="docker inspect --format '{{ .NetworkSettings.IPAddress }}'"

# Run deamonized container, e.g., $dkd base /bin/echo hello
alias dkd="docker run -d -P"

# Run interactive container, e.g., $dki base /bin/bash
alias dki="docker run -i -t -P"

# Execute interactive container, e.g., $dex base /bin/bash
alias dex="docker exec -i -t"

# Stop all containers
dstop() { docker stop $(docker ps -a -q); }

# Remove all containers
drm() { docker rm $(docker ps -a -q); }

# Stop and Remove all containers
alias drmf='docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)'

# Remove all images
dri() { docker rmi $(docker images -q); }

# Dockerfile build, e.g., $dbu tcnksm/test
dbu() { docker build -t=$1 .; }

# Show all alias related docker
dalias() { alias | grep 'docker' | sed "s/^\([^=]*\)=\(.*\)/\1 => \2/"| sed "s/['|\']//g" | sort; }

# Bash into running container
dbash() { docker exec -it $(docker ps -aqf "name=$1") bash; }

export ZSH="/home/iban/.oh-my-zsh"

#ZSH_THEME="agnoster"

ZSH_THEME="robbyrussell"

plugins=(
  aws
  docker-compose
  docker
  git
  github
  golang
  helm
  kops
  kubectl
  minikube
  nmap
  node
  npm
#  ssh-agent
  systemd
  terraform
  tmux
  vscode
)

source $ZSH/oh-my-zsh.sh

export XDG_CONFIG_HOME="$HOME/.config"
export GOPATH=$HOME/go
#export PATH=$PATH:$(go env GOPATH)/bin
export PATH="$PATH":"$HOME/.pub-cache/bin":/opt/go/bin

#source '/opt/kube-ps1/kube-ps1.sh'
#PROMPT='$(kube_ps1)'$PROMPT

alias chromium="chromium --password-store=gnome"
eval "$(starship init zsh)"

